timeout: 10s
targets:
    google.com:
        url: http://www.google.com/
    realzeit.https:
        url: https://realzeit.io/
        timeout: 5s
        spidertime: 13s
    realzeit.http:
        url: http://realzeit.io/
        spidertime: 13s
